spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/report_service"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        format_sql: "true"
server:
  port: "8083"
custom:
  url:
    account:
      get: "http://localhost:8080/backend/account/{ids}"
    operation:
      create: "http://localhost:8080//account/{uuid}/operation"
      get: "http://localhost:8080/backend/operation/{ids}"
    classifier:
      currency:
        get: "http://localhost:8081/backend/classifier/currency/{ids}"
      operation-category:
        get: "http://localhost:8081/backend/classifier/operation/category/{ids}"