spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mail_scheduler_service"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        format_sql: "true"
  mvc:
    quartz:
      job-store-type: "jdbc"
      jdbc:
        initialize-schema: "always"
        platform: "postgres"
      properties:
        "org.quartz.jobStore.driverDelegateClass": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
        "org.quartz.jobStore.tablePrefix": "quartz.QRTZ_"
server:
  port: "8085"
custom:
  url:
    mail:
      create: "http://localhost:8084/mail"