spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/account_scheduler_service"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        format_sql: "true"
  mvc:
    quartz:
      job-store-type: "jdbc"
      jdbc:
        initialize-schema: "always"
        platform: "postgres"
      properties:
        "org.quartz.jobStore.driverDelegateClass": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
        "org.quartz.jobStore.tablePrefix": "quartz.QRTZ_"
server:
  port: "8082"
custom:
  url:
    classifier:
      currency:
        get: "http://localhost:8081/classifier/currency/{uuid}"
      operation-category:
        get: "http://localhost:8081/classifier/operation/category/{uuid}"
    account:
      get: "http://localhost:8080/account/{uuid}"
    operation:
      create: "http://localhost:8080//account/{uuid}/operation"