spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/account_service"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        format_sql: "true"
server:
  port: "8080"
custom:
  url:
    classifier:
      currency:
        get: "http://localhost:8081/classifier/currency/{uuid}"
      operation-category:
        get: "http://localhost:8081/classifier/operation/category/{uuid}"